warning off

X0 = [  5; ...
        -1.3; ...
        -1.5; ...
        -2; ...
        3.1; ...
        1.1; ...
        -5.7; ...
        0.6; ...
        2.6; ...
        21; ...
        11.1; ...
        14.3; ...
        24.5; ...
        20; ...
        12; ...
        25; ...
        6; ...
        17.5 ];

Tmax = 100;
h = 5e-3;
%methods = { @body3_euler, @body3_euler_exp };
methods = { @body3_euler, @body3_euler, @body3_euler, @body3_euler };

im_coefs = [ 0.5, -0.5, -1, 1 ];
re_coefs = [ 1, 2, 0.5, 1.5 ];
coefs = complex(re_coefs, im_coefs);
hs = coefs / sum(coefs) * h;

[t, x] = composition_method(methods, hs, Tmax, X0);
%[~, x] = ode45(@body3, 0:h:Tmax, X0'); x = x'; % Dormand-Prince solution

R = real(x(1:9, :));

%% Wow, animations
try
    figure;
    an1 = animatedline(Color='r', LineWidth=1, MaximumNumPoints=750);
    an2 = animatedline(Color='g', LineWidth=1, MaximumNumPoints=750);
    an3 = animatedline(Color='b', LineWidth=1, MaximumNumPoints=750);
    view(3);
    rotate3d;
    grid on;
    xlim([-20 20]); ylim([-20 20]); zlim([-20 20]);
    for k = 1:size(x, 2)
        addpoints(an1, R(1, k), R(2, k), R(3, k));
        addpoints(an2, R(4, k), R(5, k), R(6, k));
        addpoints(an3, R(7, k), R(8, k), R(9, k));
        drawnow
    end
catch ME
    disp('Animation interrupted')
end